create table if not exists unsafe_users (
    id bigint generated by default as identity primary key,
    display_name varchar(80) not null,
    email varchar(254) unique not null,
    password_plaintext varchar(128) not null,
    profile_message text not null default '',
    failed_login_attempts integer not null default 0
);

create table if not exists secure_users (
    id bigint generated by default as identity primary key,
    display_name varchar(80) not null,
    email varchar(254) unique not null,
    password_hash text not null,
    password_salt text not null,
    password_iterations integer not null,
    profile_message varchar(500) not null default '',
    failed_login_attempts integer not null default 0
);
